PASS_THRESHOLD = 0.20      # Below -> confident PASS
FAIL_THRESHOLD = 0.40      # Above -> confident FAIL

FUSED_PASS_THRESHOLD = 0.25
FUSED_FAIL_THRESHOLD = 0.35

MAX_RECHECKS = 1

# Timing (milliseconds)
ROBOT_MOVE_DURATION   = 2000
CAMERA_CAPTURE_DELAY  = 800
ROBOT_ACTION_DURATION = 1500
SIMULATION_SPEED      = 1.0
